### ISSUE TITLE
Compilation failure - cannot find symbol

### ISSUE THREAD

**Issue by 0xWeverton** [thevalidator/trivia-solver#1]
i run: `mvn clean install`

```
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 31 source files to /home/weverton/projetos/trivia/trivia-solver/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/weverton/projetos/trivia/trivia-solver/src/main/java/ru/thevalidator/galaxytriviasolver/module/base/impl/GalaxyBaseRobotImpl.java:[56,68] cannot find symbol
  symbol:   class SolverImpl
  location: package ru.thevalidator.galaxytriviasolver.module.trivia.solver.impl
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.001 s
[INFO] Finished at: 2023-01-22T13:51:30-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project galaxy-trivia-solver: Compilation failure
[ERROR] /home/weverton/projetos/trivia/trivia-solver/src/main/java/ru/thevalidator/galaxytriviasolver/module/base/impl/GalaxyBaseRobotImpl.java:[56,68] cannot find symbol
[ERROR]   symbol:   class SolverImpl
[ERROR]   location: package ru.thevalidator.galaxytriviasolver.module.trivia.solver.impl
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
```

**Comment by thevalidator** [comment]
that's right, the code won't compile, there is no SolverImpl.class in the repository. Probably I will add it later, but for this moment I can't do this. The customer let me publish the code without the SolverImpl.class which finds the correct answer.

**Comment by 0xWeverton** [comment]
I checked the other branch "`pubver`" and it is calling correctly, but when I try to build it returns another error:
```
[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:2.1.2:launch4j (default) on project galaxy-trivia-solver: Failed to build the executable; please verify your configuration.: Icon doesn't exist. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:2.1.2:launch4j (default) on project galaxy-trivia-solver: Failed to build the executable; please verify your configuration.

```

I understand in the pom.xml file there is the code snippet <icon>${project.basedir}/src/main/resources/trivia.ico</icon> , however in the files ../main/resources/ there is not one trivia.ico file

**Comment by thevalidator** [comment]
The SolverImpl.class on that branch is for public version. In public version that implementation sends request to the remote server, checks if the user presents in DB and have permission to get the correct answer. If everything is fine it gets the correct answer, if no it gets random answer. 
According to the error, there is no icon file in repository, I will add it right now. And also you will need custom certificate for signing exe file. You may delete exe file generation stage in the pom.xml  by deleting launch4j and jsign pluguins.

**Comment by 0xWeverton** [comment]
I understand, thanks for the help, I'm using linux with a fedora distribution, do I necessarily have to build with windows or i can run in linux?
I followed your instructions to remove the two plugins and managed to build with the `pubver` branch, now my next step is to get the project running on my linux 
![image](https://user-images.githubusercontent.com/57471470/213935933-262e2cd1-4ca4-4350-a43b-96a31d55825f.png)

**Comment by thevalidator** [comment]
you can run linux, it doesn't matter, actually this app works on my linux machine. I've added missing icons, but probably there are some more extra files you will need, if this happens. tell me. Because I didn't thought that anyone will be interested in this app, so I just published the code for my purpose, and as this app was made for the customer, I don't have permission to publish some part of the code
